# Change these first
owner: prevter # Your GitHub organization or username, where this repository lives
repo: level-thumbnails-status # The name of this repository

sites:
  - name: Website
    url: https://levelthumbs.prevter.me/
  - name: REST API
    url: https://levelthumbs.prevter.me/user/1
  - name: Thumbnails
    url: https://levelthumbs.prevter.me/thumbnail/1/info

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /level-thumbnails-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Level Thumbnails
  introTitle: Server status for Level Thumbnails
  introMessage: 
  navbar:
    - title: Status
      href: /level-thumbnails-status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
